<template>
  <div class="space-y-6">
    <!-- Page Header -->
    <div
      class="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4"
    >
      <div>
        <h1 class="text-2xl font-bold text-white">Settings</h1>
        <p class="text-gray-500 mt-1">
          Manage system configuration and preferences
        </p>
      </div>
    </div>

    <!-- Settings Sections -->
    <div class="grid grid-cols-1 lg:grid-cols-3 gap-6">
      <!-- General Settings -->
      <div class="lg:col-span-2 space-y-6">
        <!-- TradingView Webhook Section -->
        <div class="card p-6">
          <h2 class="text-lg font-semibold text-white mb-4">
            TradingView Webhook
          </h2>
          <p class="text-sm text-gray-500 mb-4">
            This is the system-wide webhook URL for TradingView alerts. All
            users will use this webhook.
          </p>

          <div class="space-y-4">
            <div>
              <label class="block text-sm font-medium text-gray-300 mb-2">
                Webhook URL
              </label>
              <div class="flex gap-2">
                <input
                  :value="webhookUrl"
                  readonly
                  class="flex-1 px-4 py-2 rounded-xl border border-dark-600 bg-dark-700 text-white font-mono text-sm"
                />
                <button
                  @click="copyWebhook"
                  class="px-4 py-2 border border-dark-600 rounded-xl hover:bg-dark-800 transition-colors"
                  title="Copy URL"
                >
                  <svg
                    class="w-5 h-5 text-gray-400"
                    fill="none"
                    stroke="currentColor"
                    viewBox="0 0 24 24"
                  >
                    <path
                      stroke-linecap="round"
                      stroke-linejoin="round"
                      stroke-width="2"
                      d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z"
                    />
                  </svg>
                </button>
                <button
                  @click="regenerateWebhook"
                  :disabled="isRegenerating"
                  class="px-4 py-2 border border-dark-600 rounded-xl hover:bg-dark-800 transition-colors"
                  title="Regenerate URL"
                >
                  <svg
                    class="w-5 h-5 text-gray-400"
                    :class="{ 'animate-spin': isRegenerating }"
                    fill="none"
                    stroke="currentColor"
                    viewBox="0 0 24 24"
                  >
                    <path
                      stroke-linecap="round"
                      stroke-linejoin="round"
                      stroke-width="2"
                      d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15"
                    />
                  </svg>
                </button>
              </div>
            </div>

            <!-- Webhook Info -->
            <div class="p-4 bg-dark-700 rounded-xl">
              <h4 class="font-medium text-white mb-3">
                📊 TradingView Setup Guide
              </h4>

              <ol
                class="text-sm text-gray-400 space-y-2 list-decimal list-inside"
              >
                <li>
                  Import <strong>MaticTradeStrategy.pine</strong> to TradingView
                </li>
                <li>Apply to chart with desired trading pair</li>
                <li>
                  In indicator settings, set
                  <strong>Trading Symbol</strong> (e.g. BTCUSDT)
                </li>
                <li>Right-click indicator → <strong>Add Alert</strong></li>
                <li>Condition: Select <strong>"MaticTradeStrategy"</strong></li>
                <li>
                  Alert actions: Check
                  <strong>"Any alert() function call"</strong>
                </li>
                <li>Notifications → Enable <strong>Webhook URL</strong></li>
                <li>Paste the <strong>Webhook URL</strong> above</li>
                <li>Message: Leave empty (auto-generated by script)</li>
                <li>Click <strong>Create</strong> - Done! 🎉</li>
              </ol>

              <div class="mt-4 p-3 bg-green-900/20 rounded-lg">
                <p class="text-xs text-green-300">
                  <strong>✅ Automatic:</strong> Pine Script will automatically
                  send the correct JSON signals for all events (open, close, SL,
                  TP, BEP). No manual alert message needed!
                </p>
              </div>

              <div class="mt-3 p-3 bg-blue-900/20 rounded-lg">
                <p class="text-xs text-blue-300">
                  <strong>💡 Tip:</strong> Users set their own leverage & order
                  size in their dashboard. The webhook signal just triggers the
                  trade execution.
                </p>
              </div>
            </div>
          </div>
        </div>

        <!-- Platform Settings -->
        <div class="card p-6">
          <h2 class="text-lg font-semibold text-white mb-4">
            Platform Settings
          </h2>
          <div class="space-y-4">
            <div>
              <label class="block text-sm font-medium text-gray-300 mb-2">
                Platform Name
              </label>
              <input
                v-model="settings.platformName"
                type="text"
                class="w-full px-4 py-2 rounded-xl border border-dark-600 bg-dark-800 text-white placeholder-gray-500 focus:outline-none focus:ring-2 focus:ring-primary-500"
                placeholder="MaticTrade"
              />
            </div>
            <div>
              <label class="block text-sm font-medium text-gray-300 mb-2">
                Support Email
              </label>
              <input
                v-model="settings.supportEmail"
                type="email"
                class="w-full px-4 py-2 rounded-xl border border-dark-600 bg-dark-800 text-white placeholder-gray-500 focus:outline-none focus:ring-2 focus:ring-primary-500"
                placeholder="support@matictrade.com"
              />
            </div>
            <div class="flex items-center justify-between">
              <div>
                <p class="text-sm font-medium text-gray-300">
                  Maintenance Mode
                </p>
                <p class="text-xs text-gray-500">
                  Enable to show maintenance page to users
                </p>
              </div>
              <button
                @click="settings.maintenanceMode = !settings.maintenanceMode"
                :class="[
                  'relative inline-flex h-6 w-11 items-center rounded-full transition-colors',
                  settings.maintenanceMode ? 'bg-primary-500' : 'bg-dark-600',
                ]"
              >
                <span
                  :class="[
                    'inline-block h-4 w-4 transform rounded-full bg-white transition-transform',
                    settings.maintenanceMode
                      ? 'translate-x-6'
                      : 'translate-x-1',
                  ]"
                />
              </button>
            </div>
          </div>
        </div>

        <!-- Notification Settings -->
        <div class="card p-6">
          <h2 class="text-lg font-semibold text-white mb-4">
            Notification Settings
          </h2>
          <div class="space-y-4">
            <div class="flex items-center justify-between">
              <div>
                <p class="text-sm font-medium text-gray-300">
                  Email Notifications
                </p>
                <p class="text-xs text-gray-500">
                  Send email alerts for important events
                </p>
              </div>
              <button
                @click="
                  settings.emailNotifications = !settings.emailNotifications
                "
                :class="[
                  'relative inline-flex h-6 w-11 items-center rounded-full transition-colors',
                  settings.emailNotifications
                    ? 'bg-primary-500'
                    : 'bg-dark-600',
                ]"
              >
                <span
                  :class="[
                    'inline-block h-4 w-4 transform rounded-full bg-white transition-transform',
                    settings.emailNotifications
                      ? 'translate-x-6'
                      : 'translate-x-1',
                  ]"
                />
              </button>
            </div>
            <div class="flex items-center justify-between">
              <div>
                <p class="text-sm font-medium text-gray-300">
                  Telegram Notifications
                </p>
                <p class="text-xs text-gray-500">
                  Send alerts via Telegram bot
                </p>
              </div>
              <button
                @click="
                  settings.telegramNotifications =
                    !settings.telegramNotifications
                "
                :class="[
                  'relative inline-flex h-6 w-11 items-center rounded-full transition-colors',
                  settings.telegramNotifications
                    ? 'bg-primary-500'
                    : 'bg-dark-600',
                ]"
              >
                <span
                  :class="[
                    'inline-block h-4 w-4 transform rounded-full bg-white transition-transform',
                    settings.telegramNotifications
                      ? 'translate-x-6'
                      : 'translate-x-1',
                  ]"
                />
              </button>
            </div>
          </div>
        </div>

        <!-- Homepage Settings -->
        <div class="card p-6">
          <h2 class="text-lg font-semibold text-white mb-4">
            Homepage Settings
          </h2>
          <p class="text-sm text-gray-500 mb-4">
            Configure settings for the landing page.
          </p>
          <div class="space-y-4">
            <div>
              <label class="block text-sm font-medium text-gray-300 mb-2">
                <span class="flex items-center gap-2">
                  <svg
                    class="w-4 h-4 text-green-400"
                    fill="none"
                    stroke="currentColor"
                    viewBox="0 0 24 24"
                  >
                    <path
                      stroke-linecap="round"
                      stroke-linejoin="round"
                      stroke-width="2"
                      d="M14.752 11.168l-3.197-2.132A1 1 0 0010 9.87v4.263a1 1 0 001.555.832l3.197-2.132a1 1 0 000-1.664z"
                    />
                    <path
                      stroke-linecap="round"
                      stroke-linejoin="round"
                      stroke-width="2"
                      d="M21 12a9 9 0 11-18 0 9 9 0 0118 0z"
                    />
                  </svg>
                  Watch Demo Link
                </span>
              </label>
              <input
                v-model="homepageSettings.watchDemoLink"
                type="url"
                class="w-full px-4 py-2 rounded-xl border border-dark-600 bg-dark-800 text-white placeholder-gray-500 focus:outline-none focus:ring-2 focus:ring-primary-500"
                placeholder="https://youtube.com/watch?v=xxx"
              />
              <p class="text-xs text-gray-500 mt-1">Link untuk tombol "Watch Demo" di halaman utama (kosongkan untuk scroll ke section How It Works)</p>
            </div>
          </div>
        </div>

        <!-- Social Media Links -->
        <div class="card p-6">
          <h2 class="text-lg font-semibold text-white mb-4">
            Social Media Links
          </h2>
          <p class="text-sm text-gray-500 mb-4">
            These links will be displayed in the website footer and contact
            section.
          </p>
          <div class="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <div>
              <label class="block text-sm font-medium text-gray-300 mb-2">
                <span class="flex items-center gap-2">
                  <svg
                    class="w-4 h-4 text-blue-400"
                    fill="currentColor"
                    viewBox="0 0 24 24"
                  >
                    <path
                      d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm4.64 6.8c-.15 1.58-.8 5.42-1.13 7.19-.14.75-.42 1-.68 1.03-.58.05-1.02-.38-1.58-.75-.88-.58-1.38-.94-2.23-1.5-.99-.65-.35-1.01.22-1.59.15-.15 2.71-2.48 2.76-2.69a.2.2 0 00-.05-.18c-.06-.05-.14-.03-.21-.02-.09.02-1.49.95-4.22 2.79-.4.27-.76.41-1.08.4-.36-.01-1.04-.2-1.55-.37-.63-.2-1.12-.31-1.08-.66.02-.18.27-.36.74-.55 2.92-1.27 4.86-2.11 5.83-2.51 2.78-1.16 3.35-1.36 3.73-1.36.08 0 .27.02.39.12.1.08.13.19.14.27-.01.06.01.24 0 .37z"
                    />
                  </svg>
                  Telegram Group/Channel
                </span>
              </label>
              <input
                v-model="socialLinks.telegram"
                type="url"
                class="w-full px-4 py-2 rounded-xl border border-dark-600 bg-dark-800 text-white placeholder-gray-500 focus:outline-none focus:ring-2 focus:ring-primary-500"
                placeholder="https://t.me/yourgroup"
              />
              <p class="text-xs text-gray-500 mt-1">For footer social icons</p>
            </div>
            <div>
              <label class="block text-sm font-medium text-gray-300 mb-2">
                <span class="flex items-center gap-2">
                  <svg
                    class="w-4 h-4 text-green-400"
                    fill="currentColor"
                    viewBox="0 0 24 24"
                  >
                    <path
                      d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm4.64 6.8c-.15 1.58-.8 5.42-1.13 7.19-.14.75-.42 1-.68 1.03-.58.05-1.02-.38-1.58-.75-.88-.58-1.38-.94-2.23-1.5-.99-.65-.35-1.01.22-1.59.15-.15 2.71-2.48 2.76-2.69a.2.2 0 00-.05-.18c-.06-.05-.14-.03-.21-.02-.09.02-1.49.95-4.22 2.79-.4.27-.76.41-1.08.4-.36-.01-1.04-.2-1.55-.37-.63-.2-1.12-.31-1.08-.66.02-.18.27-.36.74-.55 2.92-1.27 4.86-2.11 5.83-2.51 2.78-1.16 3.35-1.36 3.73-1.36.08 0 .27.02.39.12.1.08.13.19.14.27-.01.06.01.24 0 .37z"
                    />
                  </svg>
                  Contact Telegram (Admin)
                </span>
              </label>
              <input
                v-model="socialLinks.contactTelegram"
                type="url"
                class="w-full px-4 py-2 rounded-xl border border-dark-600 bg-dark-800 text-white placeholder-gray-500 focus:outline-none focus:ring-2 focus:ring-primary-500"
                placeholder="https://t.me/yourusername"
              />
              <p class="text-xs text-gray-500 mt-1">For "Contact on Telegram" button</p>
            </div>
            <div>
              <label class="block text-sm font-medium text-gray-300 mb-2">
                <span class="flex items-center gap-2">
                  <svg
                    class="w-4 h-4 text-gray-400"
                    fill="currentColor"
                    viewBox="0 0 24 24"
                  >
                    <path
                      d="M18.244 2.25h3.308l-7.227 8.26 8.502 11.24H16.17l-5.214-6.817L4.99 21.75H1.68l7.73-8.835L1.254 2.25H8.08l4.713 6.231zm-1.161 17.52h1.833L7.084 4.126H5.117z"
                    />
                  </svg>
                  Twitter / X
                </span>
              </label>
              <input
                v-model="socialLinks.twitter"
                type="url"
                class="w-full px-4 py-2 rounded-xl border border-dark-600 bg-dark-800 text-white placeholder-gray-500 focus:outline-none focus:ring-2 focus:ring-primary-500"
                placeholder="https://x.com/yourhandle"
              />
            </div>
            <div>
              <label class="block text-sm font-medium text-gray-300 mb-2">
                <span class="flex items-center gap-2">
                  <svg
                    class="w-4 h-4 text-pink-400"
                    fill="currentColor"
                    viewBox="0 0 24 24"
                  >
                    <path
                      d="M12 2.163c3.204 0 3.584.012 4.85.07 3.252.148 4.771 1.691 4.919 4.919.058 1.265.069 1.645.069 4.849 0 3.205-.012 3.584-.069 4.849-.149 3.225-1.664 4.771-4.919 4.919-1.266.058-1.644.07-4.85.07-3.204 0-3.584-.012-4.849-.07-3.26-.149-4.771-1.699-4.919-4.92-.058-1.265-.07-1.644-.07-4.849 0-3.204.013-3.583.07-4.849.149-3.227 1.664-4.771 4.919-4.919 1.266-.057 1.645-.069 4.849-.069zm0-2.163c-3.259 0-3.667.014-4.947.072-4.358.2-6.78 2.618-6.98 6.98-.059 1.281-.073 1.689-.073 4.948 0 3.259.014 3.668.072 4.948.2 4.358 2.618 6.78 6.98 6.98 1.281.058 1.689.072 4.948.072 3.259 0 3.668-.014 4.948-.072 4.354-.2 6.782-2.618 6.979-6.98.059-1.28.073-1.689.073-4.948 0-3.259-.014-3.667-.072-4.947-.196-4.354-2.617-6.78-6.979-6.98-1.281-.059-1.69-.073-4.949-.073zm0 5.838c-3.403 0-6.162 2.759-6.162 6.162s2.759 6.163 6.162 6.163 6.162-2.759 6.162-6.163c0-3.403-2.759-6.162-6.162-6.162zm0 10.162c-2.209 0-4-1.79-4-4 0-2.209 1.791-4 4-4s4 1.791 4 4c0 2.21-1.791 4-4 4zm6.406-11.845c-.796 0-1.441.645-1.441 1.44s.645 1.44 1.441 1.44c.795 0 1.439-.645 1.439-1.44s-.644-1.44-1.439-1.44z"
                    />
                  </svg>
                  Instagram
                </span>
              </label>
              <input
                v-model="socialLinks.instagram"
                type="url"
                class="w-full px-4 py-2 rounded-xl border border-dark-600 bg-dark-800 text-white placeholder-gray-500 focus:outline-none focus:ring-2 focus:ring-primary-500"
                placeholder="https://instagram.com/yourprofile"
              />
            </div>
            <div>
              <label class="block text-sm font-medium text-gray-300 mb-2">
                <span class="flex items-center gap-2">
                  <svg
                    class="w-4 h-4 text-blue-600"
                    fill="currentColor"
                    viewBox="0 0 24 24"
                  >
                    <path
                      d="M24 12.073c0-6.627-5.373-12-12-12s-12 5.373-12 12c0 5.99 4.388 10.954 10.125 11.854v-8.385H7.078v-3.47h3.047V9.43c0-3.007 1.792-4.669 4.533-4.669 1.312 0 2.686.235 2.686.235v2.953H15.83c-1.491 0-1.956.925-1.956 1.874v2.25h3.328l-.532 3.47h-2.796v8.385C19.612 23.027 24 18.062 24 12.073z"
                    />
                  </svg>
                  Facebook
                </span>
              </label>
              <input
                v-model="socialLinks.facebook"
                type="url"
                class="w-full px-4 py-2 rounded-xl border border-dark-600 bg-dark-800 text-white placeholder-gray-500 focus:outline-none focus:ring-2 focus:ring-primary-500"
                placeholder="https://facebook.com/yourpage"
              />
            </div>
            <div>
              <label class="block text-sm font-medium text-gray-300 mb-2">
                <span class="flex items-center gap-2">
                  <svg
                    class="w-4 h-4 text-red-500"
                    fill="currentColor"
                    viewBox="0 0 24 24"
                  >
                    <path
                      d="M23.498 6.186a3.016 3.016 0 0 0-2.122-2.136C19.505 3.545 12 3.545 12 3.545s-7.505 0-9.377.505A3.017 3.017 0 0 0 .502 6.186C0 8.07 0 12 0 12s0 3.93.502 5.814a3.016 3.016 0 0 0 2.122 2.136c1.871.505 9.376.505 9.376.505s7.505 0 9.377-.505a3.015 3.015 0 0 0 2.122-2.136C24 15.93 24 12 24 12s0-3.93-.502-5.814zM9.545 15.568V8.432L15.818 12l-6.273 3.568z"
                    />
                  </svg>
                  YouTube
                </span>
              </label>
              <input
                v-model="socialLinks.youtube"
                type="url"
                class="w-full px-4 py-2 rounded-xl border border-dark-600 bg-dark-800 text-white placeholder-gray-500 focus:outline-none focus:ring-2 focus:ring-primary-500"
                placeholder="https://youtube.com/@yourchannel"
              />
            </div>
            <div>
              <label class="block text-sm font-medium text-gray-300 mb-2">
                <span class="flex items-center gap-2">
                  <svg
                    class="w-4 h-4 text-indigo-400"
                    fill="currentColor"
                    viewBox="0 0 24 24"
                  >
                    <path
                      d="M20.317 4.3698a19.7913 19.7913 0 00-4.8851-1.5152.0741.0741 0 00-.0785.0371c-.211.3753-.4447.8648-.6083 1.2495-1.8447-.2762-3.68-.2762-5.4868 0-.1636-.3933-.4058-.8742-.6177-1.2495a.077.077 0 00-.0785-.037 19.7363 19.7363 0 00-4.8852 1.515.0699.0699 0 00-.0321.0277C.5334 9.0458-.319 13.5799.0992 18.0578a.0824.0824 0 00.0312.0561c2.0528 1.5076 4.0413 2.4228 5.9929 3.0294a.0777.0777 0 00.0842-.0276c.4616-.6304.8731-1.2952 1.226-1.9942a.076.076 0 00-.0416-.1057c-.6528-.2476-1.2743-.5495-1.8722-.8923a.077.077 0 01-.0076-.1277c.1258-.0943.2517-.1923.3718-.2914a.0743.0743 0 01.0776-.0105c3.9278 1.7933 8.18 1.7933 12.0614 0a.0739.0739 0 01.0785.0095c.1202.099.246.1981.3728.2924a.077.077 0 01-.0066.1276 12.2986 12.2986 0 01-1.873.8914.0766.0766 0 00-.0407.1067c.3604.698.7719 1.3628 1.225 1.9932a.076.076 0 00.0842.0286c1.961-.6067 3.9495-1.5219 6.0023-3.0294a.077.077 0 00.0313-.0552c.5004-5.177-.8382-9.6739-3.5485-13.6604a.061.061 0 00-.0312-.0286zM8.02 15.3312c-1.1825 0-2.1569-1.0857-2.1569-2.419 0-1.3332.9555-2.4189 2.157-2.4189 1.2108 0 2.1757 1.0952 2.1568 2.419 0 1.3332-.9555 2.4189-2.1569 2.4189zm7.9748 0c-1.1825 0-2.1569-1.0857-2.1569-2.419 0-1.3332.9554-2.4189 2.1569-2.4189 1.2108 0 2.1757 1.0952 2.1568 2.419 0 1.3332-.946 2.4189-2.1568 2.4189z"
                    />
                  </svg>
                  Discord
                </span>
              </label>
              <input
                v-model="socialLinks.discord"
                type="url"
                class="w-full px-4 py-2 rounded-xl border border-dark-600 bg-dark-800 text-white placeholder-gray-500 focus:outline-none focus:ring-2 focus:ring-primary-500"
                placeholder="https://discord.gg/yourserver"
              />
            </div>
          </div>
        </div>
      </div>

      <!-- Sidebar Info -->
      <div class="space-y-6">
        <!-- Quick Stats -->
        <div class="card p-6">
          <h3 class="text-lg font-semibold text-white mb-4">System Info</h3>
          <div class="space-y-3">
            <div class="flex justify-between">
              <span class="text-sm text-gray-500">Version</span>
              <span class="text-sm font-medium text-white">{{
                systemInfo.version
              }}</span>
            </div>
            <div class="flex justify-between">
              <span class="text-sm text-gray-500">Last Updated</span>
              <span class="text-sm font-medium text-white">{{
                formatLastUpdated(systemInfo.timestamp)
              }}</span>
            </div>
            <div class="flex justify-between">
              <span class="text-sm text-gray-500">Environment</span>
              <span
                class="text-sm font-medium"
                :class="
                  systemInfo.environment === 'production'
                    ? 'text-green-500'
                    : 'text-yellow-500'
                "
              >
                {{ capitalizeFirst(systemInfo.environment) }}
              </span>
            </div>
          </div>
        </div>

        <!-- Danger Zone -->
        <div class="card p-6 border-red-900/30">
          <h3 class="text-lg font-semibold text-red-600 mb-4">Danger Zone</h3>
          <div class="space-y-3">
            <button
              @click="clearAllCaches"
              class="w-full px-4 py-2 text-sm text-red-600 border border-red-900/30 rounded-xl hover:bg-red-900/10 transition-colors"
            >
              Clear All Caches
            </button>
            <button
              @click="resetSystemSettings"
              class="w-full px-4 py-2 text-sm text-red-600 border border-red-900/30 rounded-xl hover:bg-red-900/10 transition-colors"
            >
              Reset System Settings
            </button>
          </div>
        </div>
      </div>
    </div>

    <!-- Save Button -->
    <div class="flex justify-end">
      <button
        @click="saveSettings"
        :disabled="isSaving"
        class="flex items-center space-x-2 px-6 py-3 bg-primary-500 hover:bg-primary-600 disabled:opacity-50 text-white rounded-xl transition-colors"
      >
        <svg
          v-if="isSaving"
          class="w-4 h-4 animate-spin"
          fill="none"
          viewBox="0 0 24 24"
        >
          <circle
            class="opacity-25"
            cx="12"
            cy="12"
            r="10"
            stroke="currentColor"
            stroke-width="4"
          ></circle>
          <path
            class="opacity-75"
            fill="currentColor"
            d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"
          ></path>
        </svg>
        <span>{{ isSaving ? "Saving..." : "Save Settings" }}</span>
      </button>
    </div>
  </div>
</template>

<script setup lang="ts">
definePageMeta({
  layout: "admin",
  middleware: ["auth", "admin"],
});

const config = useRuntimeConfig();
const toast = useCustomToast();
const adminStore = useAdminStore();

const isLoading = ref(true);
const isSaving = ref(false);
const isRegenerating = ref(false);
const webhookToken = ref("");

const settings = reactive({
  platformName: "MaticTrade",
  supportEmail: "support@matictrade.com",
  maintenanceMode: false,
  emailNotifications: true,
  telegramNotifications: false,
});

// Social media links
const socialLinks = reactive({
  telegram: "",
  contactTelegram: "",
  twitter: "",
  instagram: "",
  facebook: "",
  youtube: "",
  discord: "",
});

// Homepage settings
const homepageSettings = reactive({
  watchDemoLink: "",
});

// System info for sidebar display
const systemInfo = reactive({
  version: "1.0.0",
  timestamp: new Date().toISOString(),
  environment: process.env.NODE_ENV || "development",
});

// Helper functions
const formatLastUpdated = (timestamp: string): string => {
  try {
    const date = new Date(timestamp);
    return date.toLocaleDateString("en-US", {
      year: "numeric",
      month: "short",
      day: "numeric",
    });
  } catch {
    return "Unknown";
  }
};

const capitalizeFirst = (str: string): string => {
  if (!str) return "";
  return str.charAt(0).toUpperCase() + str.slice(1);
};

const webhookFormat = `{"action": "open", "symbol": "BTCUSDT", "side": "long"}`;

// New simplified webhook format examples
const formatOpen = `{"action": "open", "symbol": "BTCUSDT", "side": "long"}`;
const formatClose = `{"action": "close", "symbol": "BTCUSDT", "side": "long"}`;
const formatSLClose = `{"action": "slclose", "symbol": "BTCUSDT", "side": "long"}`;
const formatTPClose = `{"action": "tpclose", "symbol": "BTCUSDT", "side": "long"}`;
const formatBEP = `{"action": "bep", "symbol": "BTCUSDT", "side": "long"}`;

// Generate webhook URL - uses NUXT_PUBLIC_API_BASE_URL from env
const webhookUrl = computed(() => {
  const baseUrl = config.public.apiBaseUrl || "http://localhost:3001";
  return `${baseUrl}/api/webhook/system/${webhookToken.value || "loading..."}`;
});

const copyWebhook = async () => {
  const textToCopy = webhookUrl.value;

  // Try using the modern Clipboard API first
  if (navigator.clipboard && window.isSecureContext) {
    try {
      await navigator.clipboard.writeText(textToCopy);
      toast.success("Copied!", "Webhook URL copied to clipboard");
      return;
    } catch (err) {
      // Fall through to fallback method
    }
  }

  // Fallback method using textarea
  try {
    const textArea = document.createElement("textarea");
    textArea.value = textToCopy;
    textArea.style.position = "fixed";
    textArea.style.left = "-999999px";
    textArea.style.top = "-999999px";
    document.body.appendChild(textArea);
    textArea.focus();
    textArea.select();

    const successful = document.execCommand("copy");
    document.body.removeChild(textArea);

    if (successful) {
      toast.success("Copied!", "Webhook URL copied to clipboard");
    } else {
      toast.error("Error", "Failed to copy - please copy manually");
    }
  } catch (error) {
    toast.error("Error", "Failed to copy - please copy manually");
  }
};

const regenerateWebhook = async () => {
  if (
    !confirm(
      "Are you sure? All existing TradingView alerts will need to be updated."
    )
  )
    return;

  isRegenerating.value = true;
  try {
    const result = await adminStore.regenerateWebhookToken();
    if (result?.webhookToken) {
      webhookToken.value = result.webhookToken;
      toast.success("Regenerated", "New webhook URL generated");
    }
  } catch (error: any) {
    toast.error("Error", error.message || "Failed to regenerate webhook");
  } finally {
    isRegenerating.value = false;
  }
};

const saveSettings = async () => {
  isSaving.value = true;
  try {
    await adminStore.updateSystemSettings({
      platformName: settings.platformName,
      supportEmail: settings.supportEmail,
      maintenanceMode: settings.maintenanceMode,
      emailNotifications: settings.emailNotifications,
      telegramNotifications: settings.telegramNotifications,
    });
    
    // Also save social links
    await saveSocialLinks();
    
    // Also save homepage settings
    await saveHomepageSettings();
    
    toast.success("Settings saved successfully");
  } catch (error: any) {
    toast.error(error.message || "Failed to save settings");
  } finally {
    isSaving.value = false;
  }
};

const clearAllCaches = async () => {
  if (!confirm("Are you sure you want to clear all caches?")) return;

  try {
    await adminStore.clearCache();
    toast.success("Cache cleared successfully");
  } catch (error: any) {
    toast.error(error.message || "Failed to clear cache");
  }
};

const resetSystemSettings = () => {
  if (
    !confirm("Are you sure you want to reset all system settings to defaults?")
  )
    return;

  Object.assign(settings, {
    platformName: "MaticTrade",
    supportEmail: "support@matictrade.com",
    maintenanceMode: false,
    emailNotifications: true,
    telegramNotifications: false,
  });

  toast.success("Settings reset to defaults");
};

// Load settings from backend
const loadSettings = async () => {
  isLoading.value = true;
  try {
    const data = await adminStore.getSystemSettings();
    if (data) {
      settings.platformName = data.platformName || "MaticTrade";
      settings.supportEmail = data.supportEmail || "support@matictrade.com";
      settings.maintenanceMode = data.maintenanceMode || false;
      settings.emailNotifications = data.emailNotifications ?? true;
      settings.telegramNotifications = data.telegramNotifications || false;
      webhookToken.value = data.webhookToken || "";
    }
    
    // Load social links
    await loadSocialLinks();
    
    // Load homepage settings
    await loadHomepageSettings();
  } catch (error: any) {
    console.error("Failed to load settings:", error);
  } finally {
    isLoading.value = false;
  }
};

// Load social links from backend
const loadSocialLinks = async () => {
  try {
    const baseUrl = config.public.apiBaseUrl;
    const response = await fetch(`${baseUrl}/api/settings/social`);
    const data = await response.json();
    if (data.success) {
      Object.assign(socialLinks, data.data);
    }
  } catch (error) {
    console.error("Failed to load social links:", error);
  }
};

// Save social links to backend
const saveSocialLinks = async () => {
  try {
    const token = localStorage.getItem('token');
    const baseUrl = config.public.apiBaseUrl;
    const response = await fetch(`${baseUrl}/api/settings/social`, {
      method: 'PUT',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${token}`
      },
      body: JSON.stringify(socialLinks)
    });
    const data = await response.json();
    if (data.success) {
      toast.success("Social links saved successfully");
    } else {
      throw new Error(data.message);
    }
  } catch (error: any) {
    toast.error(error.message || "Failed to save social links");
  }
};

// Load homepage settings from backend
const loadHomepageSettings = async () => {
  try {
    const baseUrl = config.public.apiBaseUrl;
    const response = await fetch(`${baseUrl}/api/settings/homepage`);
    const data = await response.json();
    if (data.success) {
      Object.assign(homepageSettings, data.data);
    }
  } catch (error) {
    console.error("Failed to load homepage settings:", error);
  }
};

// Save homepage settings to backend
const saveHomepageSettings = async () => {
  try {
    const token = localStorage.getItem('token');
    const baseUrl = config.public.apiBaseUrl;
    const response = await fetch(`${baseUrl}/api/settings/homepage`, {
      method: 'PUT',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${token}`
      },
      body: JSON.stringify(homepageSettings)
    });
    const data = await response.json();
    if (!data.success) {
      throw new Error(data.message);
    }
  } catch (error: any) {
    toast.error(error.message || "Failed to save homepage settings");
  }
};

// Initialize on mount
onMounted(() => {
  loadSettings();
});
</script>
